# Generated by Django 4.1.2 on 2024-05-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_board_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='index',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.board'),
        ),
    ]
