# Generated by Django 4.1.2 on 2024-07-07 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_remove_card_user_card_end_date_card_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cards_id',
        ),
        migrations.AddField(
            model_name='card',
            name='participants',
            field=models.ManyToManyField(related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
