# Generated by Django 5.1.7 on 2025-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('user', 'Пользователь'), ('moderator', 'Модератор')], default='user', max_length=20),
        ),
    ]
