# Generated by Django 5.1.7 on 2025-03-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
    ]
